Cloning into '/home/subuser/.texttest/tmp/texttest.30Oct195239.8/texttest/list/List-available-from-invalid-URI/.subuser/repositories/default'...
Repository id: file://invalid-uri could not be resolved.
Error when resolving repository identifier file://invalid-uri.
